In [6]:
import numpy as np
import random


In [62]:
def generate_sparse_symetric_matrix_lil(n, density):
    matrix = [[] for _ in range(n)]
    for i in range(n):
        for j in range(i, n):
            if random.random() < density:
                value = random.random()
                matrix[i].append((j, value))
                if i != j:
                    matrix[j].append((i, value))
    return matrix


size = 512
density = 0.01
sparse_matrix = generate_sparse_symetric_matrix_lil(size, density)

sparse_matrix


[[(120, 0.391998105608784),
  (291, 0.22555047169178288),
  (443, 0.9730096510653267)],
 [(42, 0.4306489763596716),
  (182, 0.5377986272856148),
  (235, 0.6909981853287916),
  (464, 0.08849719212537832),
  (488, 0.18848677669584313)],
 [(80, 0.6073772246815403),
  (277, 0.11038331566678017),
  (306, 0.06555835108198049),
  (327, 0.7429788597077439),
  (335, 0.26398899416361254)],
 [(158, 0.08249591156941571),
  (276, 0.8505857167055471),
  (367, 0.5927944885262042),
  (432, 0.17710173663682216),
  (445, 0.7773768893277804),
  (481, 0.017906931602461706)],
 [(111, 0.6572953087874387),
  (222, 0.9525454277987118),
  (313, 0.5323925120814296)],
 [(198, 0.4555760819331717),
  (207, 0.9290637433307273),
  (236, 0.5206432974010305),
  (494, 0.8317977773904626)],
 [(134, 0.5408354832123979),
  (150, 0.6509681453793115),
  (233, 0.10494912368560838),
  (334, 0.9354254151860611),
  (411, 0.7409225700604813),
  (448, 0.8133846521857839)],
 [(71, 0.5828618987454237),
  (381, 0.3316728934744081),


In [ ]:
def read_matrix(filename):
    with open(filename, 'r') as f:
        n = int(f.readline().strip())
        f.readline()
        matrix = [[] for _ in range(n)]
        
        for _ in range(n):
            value, row, col = map(float, f.readline().strip().split(", "))
            matrix[int(row)].append((int(col), value))
            if row != col:
                matrix[int(col)].append((int(row), value))
        
    return matrix, n

def check_symmetry(matrix, n):
    for i in range(n):
        for j, value in matrix[i]:
            if not any(col == i and v == value for col, v in matrix[j]):
                return False
    return True

def power_method(matrix, n, e=1e-6, max_iter=1000):
    u = np.random.rand(n)
    u = u / np.linalg.norm(u)

    for _ in range(max_iter):
        v = np.zeros(n)
        
        for i in range(n):
            for j, value in matrix[i]:
                v[i] += value * u[j]
        
        lambda_max = np.dot(u, v)
        v_norm = np.linalg.norm(v)
        if v_norm == 0:
            break
        v = v / v_norm

        if np.linalg.norm(v - u) < e:
            break

        u = v

    numerator = 0
    denominator = np.dot(u, u)
    for i in range(n):
        for j, value in matrix[i]:
            numerator += u[i] * value * u[j]
    lambda_max = numerator / denominator

    # Calculam norma ||A * umax - lambdamax * umax||
    Au = np.zeros(n)
    for i in range(n):
        for j, value in matrix[i]:
            Au[i] += value * u[j]
    norm = np.linalg.norm(Au - lambda_max * u)

    return lambda_max, u, norm


def solve_second_problem(file_path = "", n = 0, matrix = []):
    if file_path != "":
        matrix, n = read_matrix(file_path)
    
    if check_symmetry(matrix, n):
        print("Matricea e simetrica.")
    else:
        print("Matricea nu e simetrica.")
    
    lambda_max, u_max, norm = power_method(matrix, n)
    print(f"Valoare proprie de modul maxim: {lambda_max}")
    print(f"Norma || A * u_max - lambda_max * u_max ||: {norm}")


solve_second_problem(file_path="m_rar_sim_2025_4000.txt")
# solve_second_problem(n = size, matrix = sparse_matrix)


The matrix is symmetric.
Approximate eigenvalue: 2024.9054451319598
Norm || A * u_max - lambda_max * u_max ||: 0.0007445465018655676


In [64]:
import numpy as np

def svd_analysis():
    epsilon = 1e-10
    n = random.randint(1, 10)
    p = random.randint(n, 20)

    A = np.random.rand(n, p)
    b = np.random.rand(n)

    # Descompunere SVD: A = U * S * V^T
    U, S, VT = np.linalg.svd(A, full_matrices=False)

    # 1. Valorile singulare
    print("Valorile singulare ale lui A:", S)

    # 2. Rangul matricei A
    rang = np.sum(S > epsilon)
    print("Rangul lui A:", rang)

    # 3. Numarul de conditionare (raportul dintre cea mai mare valoare ingulara si cea mai mica valoare singulara strict pozitiva)
    cond_number = S[0] / S[-1] if S[-1] > epsilon else np.inf
    print("Numarul de conditionare:", cond_number)

    # 4. Pseudoinversa Moore-Penrose: A^T = V * S^T * U^T
    S_inv = np.diag(1 / S)
    A_pseudo = VT.T @ S_inv @ U.T
    print("Pseudoinversa lui A:\n", A_pseudo)

    # 5. Solutia x^T = A^T * b
    x_pseudo = A_pseudo @ b
    print("Solutia x^I a sistemului Ax = b:", x_pseudo)

    # 6. Norma ||b - A x^T||_2
    residuum = np.linalg.norm(b - A @ x_pseudo)
    print("Norma ||b - Ax^I||2:", residuum)

svd_analysis()


Valorile singulare ale lui A: [3.26788322 1.01490308 0.71797174 0.43720769 0.14570131]
Rangul lui A: 5
Numarul de conditionare: 22.428647203561113
Pseudoinversa lui A:
 [[-0.0308903  -0.42198695 -0.50008525  1.08573117  0.14488043]
 [-0.01376171  0.04685865 -0.20874898  2.32328669 -1.46941202]
 [-0.9711202   0.87529665  0.79202925 -0.58269348 -0.02949677]
 [ 1.97112244 -0.27665329  0.52997198 -4.67352646  2.06026923]
 [ 0.55962469 -0.12374949 -0.08154964  0.314373   -0.17105689]
 [-0.28607603  1.00589658 -0.44203909 -1.74185893  1.41839226]
 [-0.26579562 -0.97231537  0.40718729  2.10944885 -0.82084959]]
Solutia x^I a sistemului Ax = b: [ 0.12481449  0.50488125 -0.4992884   0.43291467  0.50076866 -0.48469954
  0.30480981]
Norma ||b - Ax^I||2: 6.638168205731153e-16
