In [1]:
import numpy as np

### Descompunere LU 
- Cand U are 1 pe diag pp
- Fara vector dU

In [54]:
import numpy as np

def lu_decomposition_v1(A):
    n = A.shape[0]
    L = np.zeros((n, n))
    U = np.eye(n)
    
    for p in range(n):
        for i in range(p, n):
            sum_l = sum(L[i, k] * U[k, p] for k in range(p))
            L[i, p] = A[i, p] - sum_l
        
        for i in range(p + 1, n):
            sum_u = sum(L[p, k] * U[k, i] for k in range(p))
            if L[p, p] == 0:
                raise ValueError("am gasit un minor cu det=0, deci nu se poate continua cu LU")
            U[p, i] = (A[p, i] - sum_u) / L[p, p]
    
    return L, U

try:
    A = np.array([[4, 4, 3],
                [2, 2, 5.5],
                [6, 3, 12.5]], dtype=float)

    L, U = lu_decomposition_v1(A)

    print("Matricea L:")
    print(L)
    print("\nMatricea U:")
    print(U)

    print("\nVerificare A = LU:")
    print(np.dot(L, U))
except ValueError as e:
    print(f'eroare: {e}')

eroare: am gasit un minor cu det=0, deci nu se poate continua cu LU


### Descompunere LU 
- Cand U are vectorul dU pe diagonala principala

In [38]:
def lu_decomposition(A, dU=None):
    n = A.shape[0]
    
    if dU is None:
        dU = np.ones(n)
    
    L = np.zeros((n, n))
    U = np.zeros((n, n))
    
    for i in range(n):
        U[i, i] = dU[i]
    
    if A[0, 0] == 0 or U[0, 0] == 0:
        raise ValueError("am gasit un minor cu det=0, deci nu se poate continua cu LU")
    
    L[0, 0] = A[0, 0] / U[0, 0]
    
    for j in range(1, n):
        U[0, j] = A[0, j] / L[0, 0]
    
    for i in range(1, n):
        L[i, 0] = A[i, 0] / U[0, 0]
    
    for p in range(1, n):
        sum_l = 0
        for k in range(p):
            sum_l += L[p, k] * U[k, p]
        
        if A[p, p] - sum_l == 0 or U[p, p] == 0:
            raise ValueError(f"am gasit un minor cu det=0 (pasul {p}), deci nu se poate continua cu LU")
        
        L[p, p] = (A[p, p] - sum_l) / U[p, p]
        
        for j in range(p+1, n):
            sum_u = 0
            for k in range(p):
                sum_u += L[p, k] * U[k, j]
            
            U[p, j] = (A[p, j] - sum_u) / L[p, p]
        
        for i in range(p+1, n):
            sum_l = 0
            for k in range(p):
                sum_l += L[i, k] * U[k, p]
            L[i, p] = (A[i, p] - sum_l) / U[p, p]
    
    return L, U

In [55]:
A = np.array([[4, 2, 3],
              [2, 7, 5.5],
              [6, 3, 12.5]], dtype=float)

A.shape

(3, 3)

In [56]:
A = np.array([[4, 2, 3],
              [2, 7, 5.5],
              [6, 3, 12.5]], dtype=float)

dU = np.array([2, 3, 4])

valid = True

n = A.shape[0]

for k in range(1,n+1):
    Ak = A[:k, :k]
    det = np.linalg.det(Ak)

    if det == 0:
        valid = False
        print("nu se poate calcula o descompunere LU")

        break
 
if valid:
    L, U = lu_decomposition(A,dU)

print("natricea L:")
print(L)
print("\nmatricea U:")
print(U)

LU = np.dot(L, U)
print("\nverificare A = LU:")
print(LU)

print("\ndU =", dU.tolist())

Matricea L:
[[2. 0. 0.]
 [1. 2. 0.]
 [3. 0. 2.]]

Matricea U:
[[2.  1.  1.5]
 [0.  3.  2. ]
 [0.  0.  4. ]]

Verificare A = LU:
[[ 4.   2.   3. ]
 [ 2.   7.   5.5]
 [ 6.   3.  12.5]]

dU = [2, 3, 4]


In [64]:
def lu_decomposition_v2(A, dU=None):
    n = A.shape[0]
    
    A_copy = A.copy()
    
    for i in range(n):
        A_copy[i, i] = dU[i]
    
    if A_copy[0, 0] == 0 or dU[0] == 0:
        raise ValueError("am gasit un minor cu det=0, deci nu se poate continua cu LU")
    
    A_copy[0, 0] = A_copy[0, 0] / dU[0]
    
    for j in range(1, n):
        A_copy[0, j] = A_copy[0, j] / A_copy[0, 0]
    
    for i in range(1, n):
        A_copy[i, 0] = A_copy[i, 0] / dU[0]
    
    for p in range(1, n):
        sum_l = 0
        for k in range(p):
            sum_l += A_copy[p, k] * dU[k]
        
        if A_copy[p, p] - sum_l == 0 or dU[p] == 0:
            raise ValueError(f"am gasit un minor cu det=0 (pasul {p}), deci nu se poate continua cu LU")
        
        A_copy[p, p] = (A_copy[p, p] - sum_l) / dU[p]
        
        for j in range(p+1, n):
            sum_u = 0
            for k in range(p):
                sum_u += A_copy[p, k] * dU[k]
            
            A_copy[p, j] = (A_copy[p, j] - sum_u) / (A_copy[p, p])
        
        for i in range(p+1, n):
            sum_l = 0
            for k in range(p):
                sum_l += A_copy[i, k] * dU[k]
            
            A_copy[i, p] = (A_copy[i, p] - sum_l) / dU[p]
    
    return A_copy

In [58]:
def lu_decomposition_inplace(A, dU=None):
    n = A.shape[0]
    
    # Creăm o copie a lui A pentru a nu modifica matricea originală
    A_copy = A.copy()
    
    if dU is None:
        dU = np.ones(n)
    
    # Verificăm dacă primul element este zero
    if A_copy[0, 0] == 0 or dU[0] == 0:
        raise ValueError("am gasit un minor cu det=0, deci nu se poate continua cu LU")
    
    # Inițializăm primul element al lui L (salvat în diagonala principală)
    A_copy[0, 0] = A_copy[0, 0] / dU[0]
    
    # Calculăm prima linie de U (elementele de deasupra diagonalei principale)
    for j in range(1, n):
        A_copy[0, j] = A_copy[0, j] / A_copy[0, 0]
    
    # Calculăm prima coloană de L (elementele de sub diagonala principală)
    for i in range(1, n):
        A_copy[i, 0] = A_copy[i, 0] / dU[0]
    
    # Procesăm restul matricei
    for p in range(1, n):
        # Calculăm L[p, p]
        sum_l = 0
        for k in range(p):
            sum_l += A_copy[p, k] * A_copy[k, p] * dU[k]
        
        if A_copy[p, p] - sum_l == 0 or dU[p] == 0:
            raise ValueError(f"am gasit un minor cu det=0 (pasul {p}), deci nu se poate continua cu LU")
        
        A_copy[p, p] = (A_copy[p, p] - sum_l) / dU[p]
        
        # Calculăm rândul p din U
        for j in range(p+1, n):
            sum_u = 0
            for k in range(p):
                sum_u += A_copy[p, k] * A_copy[k, j] * dU[k]
            
            A_copy[p, j] = (A_copy[p, j] - sum_u) / (A_copy[p, p] * dU[p])
        
        # Calculăm coloana p din L
        for i in range(p+1, n):
            sum_l = 0
            for k in range(p):
                sum_l += A_copy[i, k] * A_copy[k, p] * dU[k]
            
            A_copy[i, p] = (A_copy[i, p] - sum_l) / dU[p]
    
    return A_copy

In [65]:
A = np.array([[4, 2, 3],
              [2, 7, 5.5],
              [6, 3, 12.5]], dtype=float)

dU = np.array([2, 3, 4])

valid = True

n = A.shape[0]

for k in range(1,n+1):
    Ak = A[:k, :k]
    det = np.linalg.det(Ak)

    if det == 0:
        valid = False
        print("nu se poate calcula o descompunere LU")

        break
 
if valid:
    A_new = lu_decomposition_v2(A,dU)

print(A_new)

LU = np.dot(L, U)


[[ 1.          2.          3.        ]
 [ 1.          0.33333333 10.5       ]
 [ 3.         -1.          0.25      ]]
