In [1]:
import numpy as np

### Descompunere LU 
- Cand U are 1 pe diag pp
- Fara vector dU

In [46]:
import numpy as np

def lu_decomposition_v1(A):
    n = A.shape[0]
    L = np.zeros((n, n))
    U = np.eye(n)
    
    for p in range(n):
        for i in range(p, n):
            sum_l = sum(L[i, k] * U[k, p] for k in range(p))
            L[i, p] = A[i, p] - sum_l
        
        for i in range(p + 1, n):
            sum_u = sum(L[p, k] * U[k, i] for k in range(p))
            if L[p, p] == 0:
                raise ValueError("am gasit un minor cu det=0, deci nu se poate continua cu LU")
            U[p, i] = (A[p, i] - sum_u) / L[p, p]
    
    return L, U

A = np.array([[4, 4, 3],
              [2, 2, 5.5],
              [6, 3, 12.5]], dtype=float)

L, U = lu_decomposition_v1(A)

print("Matricea L:")
print(L)
print("\nMatricea U:")
print(U)

print("\nVerificare A = LU:")
print(np.dot(L, U))


ValueError: am gasit un minor cu det=0, deci nu se poate continua cu LU

In [38]:
def lu_decomposition(A, dU=None):
    n = A.shape[0]
    
    if dU is None:
        dU = np.ones(n)
    
    L = np.zeros((n, n))
    U = np.zeros((n, n))
    
    for i in range(n):
        U[i, i] = dU[i]
    
    L[0, 0] = A[0, 0] / U[0, 0]
    
    for j in range(1, n):
        U[0, j] = A[0, j] / L[0, 0]
    
    for i in range(1, n):
        L[i, 0] = A[i, 0] / U[0, 0]
    
    for p in range(1, n):
        sum_l = 0
        for k in range(p):
            sum_l += L[p, k] * U[k, p]
        L[p, p] = (A[p, p] - sum_l) / U[p, p]  
        # L[1,1] = (7-1*1)/3 = 2
        # L[2,2] = (12.5-3*0)/4 = 3.125
        
        for j in range(p+1, n):
            sum_u = 0
            for k in range(p):
                sum_u += L[p, k] * U[k, j]
            U[p, j] = (A[p, j] - sum_u) / L[p, p]
    
        for i in range(p+1, n):
            sum_l = 0
            for k in range(p):
                sum_l += L[i, k] * U[k, p]
            L[i, p] = (A[i, p] - sum_l) / U[p, p]
    
    return L, U

In [39]:
A = np.array([[4, 2, 3],
              [2, 7, 5.5],
              [6, 3, 12.5]], dtype=float)

dU = np.array([2, 3, 4])

valid = True

for k in range(1,n+1):
    Ak = A[:k, :k]
    det = np.linalg.det(Ak)

    if det == 0:
        valid = False
        print("Nu se poate calcula o descompunere LU")

        break
 
if valid:
    L, U = lu_decomposition(A,dU)

print("Matricea L:")
print(L)
print("\nMatricea U:")
print(U)

LU = np.dot(L, U)
print("\nVerificare A = LU:")
print(LU)

print("\ndU =", dU.tolist())

Matricea L:
[[2. 0. 0.]
 [1. 2. 0.]
 [3. 0. 2.]]

Matricea U:
[[2.  1.  1.5]
 [0.  3.  2. ]
 [0.  0.  4. ]]

Verificare A = LU:
[[ 4.   2.   3. ]
 [ 2.   7.   5.5]
 [ 6.   3.  12.5]]

dU = [2, 3, 4]
